name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 上传所有文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./          # 上传根目录下的所有文件（index.html 就在这里）
      
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4